[toolchain]
channel = "nightly-2022-09-17"
profile = "default"
targets = [ "x86_64-unknown-linux-gnu", "x86_64-pc-windows-gnu",
"x86_64-unknown-freebsd" ]
components = [ "rust-analyzer", "clippy", "rustc", "cargo", "rust-std", "rustfmt" ]
