name = "Rox"
authors = ["muppi090909"]

[[version]]
dependencies = ["xxx/yyy"]
version = "0.1.0"
[version.tarballs]
x86_64-unknown-linux-gnu = "linux"
x86_64-pc-windows-gnu = "windows"

[[version]]
dependencies = ["xxx/yyy"]
version = "0.1.1"
[version.tarballs]
x86_64-unknown-linux-gnu = "linux"
