name = "Rox"
authors = ["muppi090909"]

[[version]]
dependencies = ["xxx/yyy"]
version = "0.1.0"
[version.tarballs]
x86_64-unknown-linux-gnu = ["linux", ["xxx"]]

[[version]]
dependencies = ["xxx/yyy"]
version = "0.1.1"
[version.tarballs]
x86_64-unknown-linux-gnu = ["linux", ["xxx"]]
